
version: 2.1

jobs: 

  build:
    docker:
      - image: php:latest
    working_directory: /mnt/ramdisk
    steps:
      - checkout
      - run:
          name: Run index.php
          command: php index.php
      - run:
          name: Echo command
          command: echo "hello world"

  test:
    docker:
      - image: php:latest
    working_directory: /mnt/ramdisk
    steps:
      - run: 
          name: Test command
          command: echo "hello world"
  test2:
    docker:
      - image: php:latest
    working_directory: /mnt/ramdisk
    steps:
      - run: 
          name: Test command
          command: echo "hello world"
    



workflows:
  BuildEnviroment:
    jobs:
      - build
      - test:
          requires:
            - build

      - hold:
          type: approval
          requires:
            - test

      - test2:
          requires:
            - hold

  