version: 2.1

orbs:
  # Declare a dependency on the welcome-orb
  welcome: circleci/welcome-orb@0.4.1

# Orchestrate or schedule a set of jobs
workflows:
  # Test of CircleCI
  welcome:
    jobs:
      - welcome/run
