version: 2.1

orbs:
  # Declare a dependency on the welcome-orb
  welcome: circleci/welcome-orb@0.4.1


jobs: 
  build:
    docker:
      - image: php:latest
    steps:
      - run: echo "hello world1"
      - run: echo "hello world2"
  test:
    docker:
      - image: php:latest
    steps:
      - run: echo "hello world"
  



workflows:
  welcome:
    jobs:
      - welcome/run
  custom:
    jobs:
      - build
      - test:
        requires:
          - build
  