version: 2.1

orbs:
  # Declare a dependency on the welcome-orb
  welcome: circleci/welcome-orb@0.4.1


jobs: 
  build:
    docker:
      - run: echo "hello world"
    compose:
      - run: echo "hello world"
  test:
    test1:
      - run: echo "hello world"
    test2:
      - run: echo "hello world"
  



workflows:
  welcome:
    jobs:
      - welcome/run
  custom:
    jobs:
      - build
      - test
  