version: 2.1

orbs:
  # Declare a dependency on the welcome-orb
  welcome: circleci/welcome-orb@0.4.1


jobs: 
  build:
    docker:
      - image: php:latest
    #working_directory: /mnt/ramdisk
    steps:
      - run:
          name: test1
          command: echo "hello world1"
      - run:
          name: test2
          command: echo "hello world2"
  test:
    docker:
      - image: php:latest
    steps:
      - run: 
          name: test3
          command: echo "hello world"
    



workflows:
  welcome:
    jobs:
      - welcome/run
  custom:
    jobs:
      - build
      - test:
          requires:
            - build
  